const SCREEN_MOBILE = 768;
const SCREEN_LAPTOP = 922;
const SCREEN_DESKTOP = 1236;

const STEP_MOBILE = 2;
const STEP_LAPTOP = 3;
const STEP_DESKTOP = 4;

const DEFAULT_MOBILE = 5;
const DEFAULT_LAPTOP = 8;
const DEFAULT_LAPTOP_WIDE = 12;
const DEFAULT_DESKTOP = 16;

export {
  SCREEN_MOBILE,
  SCREEN_LAPTOP,
  SCREEN_DESKTOP,
  STEP_MOBILE,
  STEP_LAPTOP,
  STEP_DESKTOP,
  DEFAULT_MOBILE,
  DEFAULT_LAPTOP,
  DEFAULT_LAPTOP_WIDE,
  DEFAULT_DESKTOP,
};
